steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_CONTAINER}:${SHORT_SHA}',
      '-t', '${_CONTAINER}:latest',
      '.'
    ]
    dir: 'hello'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_CONTAINER}:${SHORT_SHA}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_CONTAINER}:latest'
    ]

substitutions:
  _CONTAINER: 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/jobs/info'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

images:
  - '${_CONTAINER}:${SHORT_SHA}'
  - '${_CONTAINER}:latest'